#!/bin/sh

####################################################################################################
# User-serviceable definitions
####################################################################################################

RECIPIENT=
SENDER=

####################################################################################################
# Internal definitions
####################################################################################################

HOST="$2"
UNIT="$1"
USER="$3"

domain="$(hostname --fqdn)"
recipient="${RECIPIENT:-root@$domain}"
sender="${SENDER:-$USER@$domain}"
status="$(systemctl status "$UNIT")"

echo "From: <$sender>\nTo: <$recipient>\nSubject: [$HOST] $UNIT\n\n$status" | sendmail -t
